### ISSUE TITLE
Setting tooltips cannot be translated

### ISSUE THREAD

**Issue by Madis0** [DaFuqs/PaginatedAdvancements#15]
Setting tooltips seem to be hardcoded as I cannot find a language file for them. MC 1.20.2, PA 2.4.0

**Comment by DaFuqs** [comment]
What tooltip are you referring to exactly?

**Comment by Madis0** [comment]
In #16 I translated all visible settings labels. But when the user hovers on each label, there is a different tooltip shown that cannot be translated.

**Comment by DaFuqs** [comment]
Since the tooltips stated pretty much the same thing like the setting already said, I've removed those.
Released the new version as 2.4.2, including your new translation and a german one. Thank you lots for all the PRs, too!
