### ISSUE TITLE
Trimmed russian advancement 

### ISSUE THREAD

**Issue by Kisuny** [DaFuqs/PaginatedAdvancements#25]
Some translated achievements are not displayed correctly, I have noticed often only the last word in a single line display is often not displayed.

MC: 1.19.2. 
PaginatedAdvanncements version: 2.2.1-1.19

Some example: 
<details>
<summary>Screenshots</summary>

![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/f8e05117-f407-4084-bc5d-215aee891741)
![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/2e122820-9daf-48bc-a614-0c964a863875)
 

![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/308a860b-c966-46b6-ad95-d0496ae3ac6b)
![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/8744d961-d6f8-440f-8353-32e29e0ff4c8)

</details>

And another mod for example: 
<details>
<summary>Screenshots</summary>

![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/597abed4-bd12-4f9d-ad24-b05755a65f53)
![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/3d0259ab-1645-4ab8-9d93-646a0a50ee75)

</details>

**Comment by DaFuqs** [comment]
Interesting. The vanilla advancements screen does not have that issue?

**Comment by Kisuny** [comment]
> Interesting. The vanilla advancements screen does not have that issue?

It's not all that clear-cut :DDD

On vanilla, description displays as it should, but the name of the advancement is trimmed... 
<details>
<summary>Screenshots</summary>

![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/90382430-8b71-4796-a421-75021c40b9ee)
![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/c41fb708-b1cf-4510-bb5d-57f793a0f658)
![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/67843580-8160-4c2f-a7de-9df5ede3cf26)
</details>

As with PaginatedAdvancements text larger than 1 line is displayed correctly

<details>
<summary>Screenshots</summary>

![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/68ed3e4e-d02b-4d16-b30f-cc777254fa3d)
![image](https://github.com/DaFuqs/PaginatedAdvancements/assets/56004431/e698b1ca-128f-449b-ba52-634183dab079)

</details>

**Comment by DaFuqs** [comment]
Wack. Alright, I will see what I can do, ty! 😄

**Comment by Kisuny** [comment]
Just in case I checked without any optimization mods, only with PaginatedAdvancements - the problem is repeated

**Comment by DaFuqs** [comment]
After looking into the vanilla internals, the vanilla screen limits the width of the title to 163 pixels. Any overflow is just capped. Descriptions are wrapped using line breaks. 

Paginated Advancements does the same. I tested on 1.20.1-1.20.6 though. Could be that there was a difference in handling overflow before, in 1.19.2. But seeing that 1.20.6 was just released I am afraid I will have to budget my time and consider this one fixed on 1.20.1+ only, sorry!
