### ISSUE TITLE
[Feature request] Add an option to resize the advancements window

### ISSUE THREAD

**Issue by M-Ryba** [DaFuqs/PaginatedAdvancements#3]
Kinda like in the better advancements mod (some tabs at least with BlazeandCave's Advancements Pack are not centered, maybe it can be done better here)
Here are some screenshots showing how it looks like in better advancements mod:
![2022-07-01_18 18 06](https://user-images.githubusercontent.com/34245941/176932807-11a670f1-8532-42cd-8f5c-0381fee82d72.png)
![2022-07-01_18 18 14](https://user-images.githubusercontent.com/34245941/176932836-b40273e4-d980-479f-9674-12e0c4277e65.png)
![2022-07-01_18 18 26](https://user-images.githubusercontent.com/34245941/176932859-fcf88bc5-35a0-49d3-84e0-b4fd1961894f.png)
.

**Comment by DaFuqs** [comment]
![image](https://user-images.githubusercontent.com/26429514/229341460-3055043e-c24b-4001-8466-8debf20dac4b.png)

there we go. Looks like this is already resolved, I just did never close the issue :)
