### ISSUE TITLE
Crashes when opeing advancement screen

### ISSUE THREAD

**Issue by TheSweatyYeti** [DaFuqs/PaginatedAdvancements#4]
#### Issue Description:

Game crashes when opening advancement screen either by pressing "L" or pausing and clicking "Advancements".

#### What happens:

Game freezes, goes to loading screen saying "Saving world", and crashes to launcher

#### What is expected to happen:

Advancement screen opens with PaginatedAdvancements.

#### Steps to reproduce:

1. Open MultiMC and create an instance with Fabric installed
2. Add Fabric API, Cloth Config, ModMenu, & PaginatedAdvancements into the "Loader mods" folder
3. Launch the instance
4. Open an existing world or create a new world
5. Once loaded, press "L" (or your advancements keybind) or access the pause menu and click "Advancements"
6.  Watch as the game crashes
...

____
#### Affected Versions:

- PaginatedAdvancements: 1.1.0-1.19
- Minecraft: 1.19
- MultiMC 5: 0.6.15-3247
- Fabric Loader: 0.14.8
- Fabric API: 0.27.0+1.19
- Cloth Config: 7.0.73
- ModMenu: 4.0.4

#### Most recent log file where the issue was present: 

[Crash Report](https://pastebin.com/Sa4e96nz)

**Comment by DaFuqs** [comment]
fixed
