### ISSUE TITLE
Debug info showing when set to off in the config

### ISSUE THREAD

**Issue by MC-Clutch** [DaFuqs/PaginatedAdvancements#5]
https://user-images.githubusercontent.com/106221136/190935345-a5e22b70-e975-4843-aea7-315a797ea31b.mp4

How do I disable the info at the bottom of the menu?

**Comment by DaFuqs** [comment]
Turn off advanced tooltips.
I should make a setting dor disabling them for good. Leaving this issue open as a reminder.

**Comment by MC-Clutch** [comment]
How do I turn off advanced Tooltips? I can't find it in mod menu option, and the config.

**Comment by MC-Clutch** [comment]
Never mind, Its F3, H
