### ISSUE TITLE
Debug tooltip too large

### ISSUE THREAD

**Issue by Madis0** [DaFuqs/PaginatedAdvancements#6]
The apple advancement tooltip is unreadable in GUI scale 3, because the debug rows take all the screen space (and still don't fit). IIRC that is the "eat all foods" one. 
Maybe consider [a scrollable sidebar like AdvancementInfo](https://www.curseforge.com/minecraft/mc-mods/advancementinfo)?
![2023-04-01_22 49 34](https://user-images.githubusercontent.com/8611110/229311315-5559f51b-933e-4b25-b7e6-f9478689e142.png)

**Comment by DaFuqs** [comment]
Done via https://github.com/DaFuqs/PaginatedAdvancements/pull/9
Thanks a lot to @daWinzig for that!

Will release & backport the change to 1.19.2 shortly.
