### ISSUE TITLE
Datapack issue in 1.20+

### ISSUE THREAD

**Issue by Rektroth** [DaFuqs/PaginatedAdvancements#8]
Although the mod loads in 1.20+, playing single-player always fails.

Trying to load an existing world results in the user being greeted by the following screen:

![Screenshot (10)](https://github.com/DaFuqs/PaginatedAdvancements/assets/53879295/200b8f08-aa3f-41d5-bbbf-19fa45566c70)

```
Errors in currently selected data packs prevented the world from loading.
You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually.
```

To be clear, the selected world need not have any non-vanilla data packs loaded for this to occur.

Trying to create a new world results in a crash.

```
The game crashed whilst mouseclicked event handler
Error: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_161 failed
```

Haven't tested multiplayer.

**Comment by DaFuqs** [comment]
Both mod and datapack definitely need to be updated to 1.20.
Currently pretty busy with rl, but I hope I will get an update out in a week

**Comment by DaFuqs** [comment]
1.20 is out!
